#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#
#Run in an echoing pseudo-terminal

require 'pty'
PTY.spawn(*ARGV) do |r,w,pid|
  begin
    while $_ = r.gets
      STDOUT.print $_
    end
  rescue Errno::EIO
  end
end
